url: https://trying2skate.github.io
baseurl: ""

# Site settings
title: trying2skate
email: trying2skate@gmail.com
description: "Maker of miniature John Wilson Pattern 99 Parabolic Blade necklaces."


# Team names, titles and social links
people:
- name: Jessica Nicosia
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Ben Wang
  pic: 2
  position: Lead Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/trying2skate/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
